# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/cmds-app/docs/discussions
    about: For open-ended questions not tied to a specific task
